#!/usr/bin/env python3
"""Tests for the palace engine — palace-map resolution/validate/render/staleness/archive.

Each test builds a throwaway fixture vault in a tempdir and drives the REAL engine
scripts (`palace-map`, `palace-context.sh`) as subprocesses with VAULT_DIR pointed at
the fixture. Stdlib unittest only — runs on /usr/bin/python3 with zero install.

    python3 -m unittest -v        (from this dir)
"""
import datetime
import json
import os
import subprocess
import tempfile
import time
import unittest
from pathlib import Path

CLAUDE_DIR = Path(os.path.expanduser("~/.claude"))
REPO_ROOT = Path(__file__).resolve().parents[2]
# The code under test is the repo's, not the copy install.sh deployed: a hand-edited
# deployed copy would otherwise pass the suite (and the push gate) for the repo.
PALACE_MAP = REPO_ROOT / "hooks" / "palace-map"
PALACE_CONTEXT = REPO_ROOT / "hooks" / "palace-context.sh"
TABLE_BEGIN = "<!-- palace-map:table:begin — generated by `palace-map render`, do not edit by hand -->"
TABLE_END = "<!-- palace-map:table:end -->"

WING_FILES = ["readme.md", "ARCHITECTURE.md", "BUGS.md", "CONTEXT.md", "DECISIONS.md", "GLOSSARY.md"]
QUIZ_LOG_HEADER = "| Date | Score | Weak topics |\n|------|-------|-------------|\n"

TEMPLATE_DIR = REPO_ROOT / "templates" / "projects" / ".template"


def make_wing(projects: Path, slug: str, status: str = "active"):
    d = projects / slug
    d.mkdir(parents=True, exist_ok=True)
    (d / "readme.md").write_text(f"---\ntags: [project]\nproject: {slug}\nstatus: {status}\n---\n# {slug}\n")
    (d / "CONTEXT.md").write_text(f"---\nproject: {slug}\n---\n# Context — {slug}\n\n## Current Focus\nstuff\n")
    for f in ("ARCHITECTURE.md", "BUGS.md", "DECISIONS.md", "GLOSSARY.md"):
        (d / f).write_text(f"# {f} — {slug}\n")
    (d / "QUIZ_LOG.md").write_text(f"# Quiz Log — {slug}\n\n{QUIZ_LOG_HEADER}")
    return d


def write_quiz_log(projects: Path, slug: str, rows):
    """rows: list of (date_str, score_str, topics_str). Overwrites QUIZ_LOG.md's table body."""
    body = QUIZ_LOG_HEADER
    for date_str, score, topics in rows:
        body += f"| {date_str} | {score} | {topics} |\n"
    (projects / slug / "QUIZ_LOG.md").write_text(f"# Quiz Log — {slug}\n\n{body}")


def make_vault(entries, wings=None, with_markers=True):
    """entries: list of mapping dicts. wings: slugs to create wing dirs for
    (defaults to every entry's slug)."""
    root = Path(tempfile.mkdtemp(prefix="palace-fix-"))
    projects = root / "projects"
    projects.mkdir(parents=True)
    (root / "claude-sessions").mkdir()
    (projects / "_mapping.json").write_text(json.dumps({"projects": entries}, indent=2))
    md = "# Map\n\nintro\n\n"
    md += (TABLE_BEGIN + "\n" + TABLE_END + "\n") if with_markers else "no markers here\n"
    md += "\n## Notes\ntail\n"
    (projects / "_mapping.md").write_text(md)
    for slug in (wings if wings is not None else [e["slug"] for e in entries]):
        make_wing(projects, slug)
    return root


def run(root, *args, extra_env=None, cwd=None):
    env = {**os.environ, "VAULT_DIR": str(root)}
    if extra_env:
        env.update(extra_env)
    r = subprocess.run([str(PALACE_MAP), *args], capture_output=True, text=True, env=env, cwd=cwd)
    return r.returncode, r.stdout, r.stderr


class TemplateFrontmatterTests(unittest.TestCase):
    def test_every_core_template_has_anticipated_queries(self):
        for name in ("readme.md", "ARCHITECTURE.md", "BUGS.md", "CONTEXT.md",
                     "DECISIONS.md", "GLOSSARY.md"):
            text = (TEMPLATE_DIR / name).read_text()
            self.assertIn("anticipated_queries:", text, f"{name} missing anticipated_queries")


class ReadmeFeaturesSectionTests(unittest.TestCase):
    def test_readme_template_has_features_section(self):
        text = (TEMPLATE_DIR / "readme.md").read_text()
        self.assertIn("## Features", text)


class ResolveTests(unittest.TestCase):
    def test_matches_and_nonmatch(self):
        root = make_vault([
            {"slug": "alpha", "globs": ["*/alpha*"], "memdir": "-a", "repo": "~/alpha"},
            {"slug": "beta", "globs": ["*/theTribe/beta*"], "memdir": "-b", "repo": "~/beta"},
        ])
        self.assertEqual(run(root, "resolve", "/x/alpha/y")[1].strip(), "alpha")
        self.assertEqual(run(root, "resolve", "/home/theTribe/beta")[1].strip(), "beta")
        self.assertEqual(run(root, "resolve", "/nope/here")[1].strip(), "")

    def test_first_match_wins_ordering(self):
        # broad glob listed BEFORE the narrower one → broad must win (locks semantics)
        root = make_vault([
            {"slug": "broad", "globs": ["*/shared*"], "memdir": "-x", "repo": "~/x"},
            {"slug": "narrow", "globs": ["*/shared/sub*"], "memdir": "-y", "repo": "~/y"},
        ])
        self.assertEqual(run(root, "resolve", "/shared/sub/z")[1].strip(), "broad")


class ValidateTests(unittest.TestCase):
    def test_clean_ok(self):
        root = make_vault([{"slug": "alpha", "globs": ["*/alpha*"], "memdir": "-a", "repo": "~/a"}])
        rc, out, _ = run(root, "validate")
        self.assertEqual(rc, 0)
        self.assertIn("OK", out)

    def test_orphan_mapping_errors(self):
        # entry with no wing dir → ERROR + exit 1 (the gallia bug)
        root = make_vault(
            [{"slug": "ghost", "globs": ["*/ghost*"], "memdir": "-g", "repo": "~/g"}],
            wings=[],  # create no wing dirs
        )
        rc, out, _ = run(root, "validate")
        self.assertEqual(rc, 1)
        self.assertIn("ERROR", out)

    def test_unwired_wing_warns(self):
        # wing dir present but not in _mapping.json → WARN, exit 0 (the dev/swizzin bug)
        root = make_vault([{"slug": "alpha", "globs": ["*/alpha*"], "memdir": "-a", "repo": "~/a"}])
        make_wing(root / "projects", "stray")
        rc, out, _ = run(root, "validate")
        self.assertEqual(rc, 0)
        self.assertIn("WARN", out)


class ReposTests(unittest.TestCase):
    """A wing can span several git repos; spine keys off the remote name."""

    ALPHA = {"slug": "alpha", "globs": ["*/alpha*"], "memdir": "-a", "repo": "~/a"}

    def test_falls_back_to_legacy_repo_field(self):
        root = make_vault([dict(self.ALPHA)])
        rc, out, _ = run(root, "repos", "alpha")
        self.assertEqual(rc, 0)
        # remote defaults to the checkout's basename, dir to the slug
        self.assertEqual(out.strip().split("\t"), ["a", "~/a", "alpha"])

    def test_lists_every_declared_repo(self):
        entry = dict(self.ALPHA, repos=[
            {"remote": "api", "path": "~/a/api", "dir": "api"},
            {"remote": "web", "path": "~/a/web", "dir": "web"},
        ])
        root = make_vault([entry])
        rc, out, _ = run(root, "repos", "alpha")
        self.assertEqual(rc, 0)
        self.assertEqual([l.split("\t")[0] for l in out.strip().splitlines()], ["api", "web"])

    def test_no_docs_dirs_is_not_a_warning(self):
        # a wing that simply doesn't use spine must stay quiet
        entry = dict(self.ALPHA, repos=[{"remote": "api", "path": "~/a/api", "dir": "api"}])
        root = make_vault([entry])
        rc, out, _ = run(root, "validate")
        self.assertEqual(rc, 0)
        self.assertNotIn("WARN", out)

    def test_missing_sibling_dir_warns(self):
        # once one repo has docs, a declared sibling without them means spine
        # auto-load silently no-ops there — that must be loud
        entry = dict(self.ALPHA, repos=[
            {"remote": "api", "path": "~/a/api", "dir": "api"},
            {"remote": "web", "path": "~/a/web", "dir": "web"},
        ])
        root = make_vault([entry])
        (root / "projects" / "alpha" / "api").mkdir()
        rc, out, _ = run(root, "validate")
        self.assertEqual(rc, 0)
        self.assertIn("WARN", out)
        self.assertIn("web", out)
        self.assertNotIn("'api' has no docs dir", out)


class RenderTests(unittest.TestCase):
    def test_idempotent(self):
        root = make_vault([{"slug": "alpha", "globs": ["*/alpha*"], "memdir": "-a", "repo": "~/a"}])
        md = root / "projects" / "_mapping.md"
        self.assertEqual(run(root, "render")[0], 0)
        first = md.read_text()
        self.assertEqual(run(root, "render")[0], 0)
        self.assertEqual(md.read_text(), first, "render must be idempotent")
        self.assertIn("`alpha`", first)

    def test_missing_markers_errors(self):
        root = make_vault([{"slug": "alpha", "globs": ["*/alpha*"], "memdir": "-a", "repo": "~/a"}],
                          with_markers=False)
        rc, out, _ = run(root, "render")
        self.assertEqual(rc, 1)
        self.assertIn("markers", out.lower())


class ArchiveTests(unittest.TestCase):
    def test_roundtrip(self):
        root = make_vault([{"slug": "alpha", "globs": ["*/alpha*"], "memdir": "-a", "repo": "~/a"}])
        readme = root / "projects" / "alpha" / "readme.md"
        run(root, "archive", "alpha")
        self.assertIn("status: archived", readme.read_text())
        run(root, "unarchive", "alpha")
        self.assertIn("status: active", readme.read_text())
        self.assertNotIn("status: archived", readme.read_text())


class StalenessTests(unittest.TestCase):
    """Drives palace-context.sh: a git repo with a commit newer than CONTEXT.md must
    trigger the staleness banner; a fresh CONTEXT.md must not."""

    def _git_repo_wing(self, root, slug, ctx_age_days):
        repo = root / "repo"
        repo.mkdir()
        subprocess.run(["git", "init", "-q", str(repo)], check=True)
        (repo / "f.txt").write_text("x")
        subprocess.run(["git", "-C", str(repo), "add", "."], check=True)
        subprocess.run(["git", "-C", str(repo), "-c", "user.email=t@t", "-c", "user.name=t",
                        "commit", "-q", "-m", "c"], check=True)
        # point the mapping's repo at the git repo, glob at a matchable cwd
        (root / "projects" / "_mapping.json").write_text(json.dumps({"projects": [
            {"slug": slug, "globs": [f"*/{slug}*"], "memdir": "-s", "repo": str(repo)}]}, indent=2))
        ctx = root / "projects" / slug / "CONTEXT.md"
        t = time.time() - ctx_age_days * 86400
        os.utime(ctx, (t, t))
        return repo

    def _run_context(self, root, cwd):
        env = {**os.environ, "VAULT_DIR": str(root), "PALACE_CLAUDE_DIR": str(CLAUDE_DIR)}
        work = root / cwd
        work.mkdir(parents=True, exist_ok=True)
        r = subprocess.run(["bash", str(PALACE_CONTEXT)], capture_output=True, text=True,
                           env=env, cwd=str(work))
        return r.stdout

    def test_stale_warns(self):
        root = make_vault([{"slug": "svc", "globs": ["*/svc*"], "memdir": "-s", "repo": "~/x"}])
        self._git_repo_wing(root, "svc", ctx_age_days=30)  # CONTEXT 30d older than commit
        out = self._run_context(root, "svc")
        self.assertIn("Palace Context — svc", out)
        self.assertIn("stale", out.lower())

    def test_fresh_no_warn(self):
        root = make_vault([{"slug": "svc", "globs": ["*/svc*"], "memdir": "-s", "repo": "~/x"}])
        self._git_repo_wing(root, "svc", ctx_age_days=0)  # CONTEXT as new as the commit
        out = self._run_context(root, "svc")
        self.assertIn("Palace Context — svc", out)
        self.assertNotIn("stale", out.lower())


class SystemDoctorTests(unittest.TestCase):
    def test_broken_install_flags_red(self):
        # Point PALACE_CLAUDE_DIR at an empty dir → settings/hooks/paths all missing → exit 1.
        root = make_vault([{"slug": "alpha", "globs": ["*/alpha*"], "memdir": "-a", "repo": "~/a"}])
        empty_claude = Path(tempfile.mkdtemp(prefix="palace-claude-"))
        rc, out, _ = run(root, "doctor", "--system",
                         extra_env={"PALACE_CLAUDE_DIR": str(empty_claude)})
        self.assertEqual(rc, 1)
        self.assertIn("RED", out)
        self.assertIn("✗", out)

    def test_hand_edited_deployed_file_flags_red(self):
        # install.sh records a sha256 manifest; a later edit in ~/.claude drifts from the repo.
        root = make_vault([{"slug": "alpha", "globs": ["*/alpha*"], "memdir": "-a", "repo": "~/a"}])
        claude = Path(tempfile.mkdtemp(prefix="palace-claude-"))
        (claude / "commands" / "palace").mkdir(parents=True)
        (claude / "commands" / "palace" / "update.md").write_text("edited by hand\n")
        (claude / ".palace-manifest").write_text("0" * 64 + "  commands/palace/update.md\n")
        out = run(root, "doctor", "--system", extra_env={"PALACE_CLAUDE_DIR": str(claude)})[1]
        self.assertIn("✗ deployed engine files match the last install", out)
        self.assertIn("commands/palace/update.md", out)

    def _doctor_with_fake_qmd(self, script):
        root = make_vault([{"slug": "alpha", "globs": ["*/alpha*"], "memdir": "-a", "repo": "~/a"}])
        bindir = Path(tempfile.mkdtemp(prefix="fake-qmd-"))
        (bindir / "qmd").write_text("#!/bin/sh\n" + script)
        (bindir / "qmd").chmod(0o755)
        path = f"{bindir}:{os.environ['PATH']}"
        return run(root, "doctor", "--system", extra_env={"PATH": path})[1]

    def test_qmd_that_crashes_flags_red(self):
        # Resolving is not enough: qmd on PATH that dies on start must show red, with its error.
        out = self._doctor_with_fake_qmd("echo \"code: 'ERR_DLOPEN_FAILED'\" >&2; exit 1\n")
        self.assertIn("✗ qmd runs", out)
        self.assertIn("ERR_DLOPEN_FAILED", out)

    def test_qmd_that_runs_is_green(self):
        out = self._doctor_with_fake_qmd("exit 0\n")
        self.assertIn("✓ qmd runs", out)

    def test_live_install_green(self):
        # Sanity: the real install should be all-green (no fixture override).
        env = {**os.environ}
        env.pop("VAULT_DIR", None)
        r = subprocess.run([str(PALACE_MAP), "doctor", "--system"],
                           capture_output=True, text=True, env=env)
        self.assertEqual(r.returncode, 0, r.stdout)
        self.assertIn("ALL GREEN", r.stdout)


class SystemDoctorGlossaryTests(unittest.TestCase):
    def test_missing_glossary_flags_red(self):
        root = make_vault([{"slug": "alpha", "globs": ["*/alpha*"], "memdir": "-a", "repo": "~/a"}])
        (root / "projects" / "alpha" / "GLOSSARY.md").unlink()
        rc, out, _ = run(root, "doctor", "--system")
        self.assertEqual(rc, 1)
        self.assertIn("GLOSSARY.md", out)


class QuizStatusTests(unittest.TestCase):
    def _repo_with_commit(self, root):
        repo = root / "repo"
        repo.mkdir()
        subprocess.run(["git", "init", "-q", str(repo)], check=True)
        (repo / "f.txt").write_text("x")
        subprocess.run(["git", "-C", str(repo), "add", "."], check=True)
        subprocess.run(["git", "-C", str(repo), "-c", "user.email=t@t", "-c", "user.name=t",
                        "commit", "-q", "-m", "c"], check=True)
        return repo

    def test_never_quizzed_active_repo_nudges(self):
        root = make_vault([{"slug": "svc", "globs": ["*/svc*"], "memdir": "-s", "repo": "~/x"}])
        repo = self._repo_with_commit(root)
        (root / "projects" / "_mapping.json").write_text(json.dumps({"projects": [
            {"slug": "svc", "globs": ["*/svc*"], "memdir": "-s", "repo": str(repo)}]}, indent=2))
        self.assertEqual(run(root, "quiz-status", "svc")[1].strip(), "NUDGE")

    def test_recently_quizzed_no_nudge(self):
        root = make_vault([{"slug": "svc", "globs": ["*/svc*"], "memdir": "-s", "repo": "~/x"}])
        repo = self._repo_with_commit(root)
        (root / "projects" / "_mapping.json").write_text(json.dumps({"projects": [
            {"slug": "svc", "globs": ["*/svc*"], "memdir": "-s", "repo": str(repo)}]}, indent=2))
        today = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d")
        write_quiz_log(root / "projects", "svc", [(today, "6/8", "none")])
        self.assertEqual(run(root, "quiz-status", "svc")[1].strip(), "")

    def test_no_activity_no_nudge(self):
        root = make_vault([{"slug": "svc", "globs": ["*/svc*"], "memdir": "-s", "repo": "~/nonexistent-x"}])
        self.assertEqual(run(root, "quiz-status", "svc")[1].strip(), "")


class ReminderTests(unittest.TestCase):
    PALACE_REMINDER = REPO_ROOT / "hooks" / "palace-reminder.sh"

    def _run_reminder(self, root, cwd):
        env = {**os.environ, "VAULT_DIR": str(root), "PALACE_CLAUDE_DIR": str(CLAUDE_DIR)}
        work = root / cwd
        work.mkdir(parents=True, exist_ok=True)
        r = subprocess.run(["bash", str(self.PALACE_REMINDER)], capture_output=True, text=True,
                           env=env, cwd=str(work))
        return r.stdout

    def test_no_match_silent(self):
        root = make_vault([{"slug": "svc", "globs": ["*/svc*"], "memdir": "-s", "repo": "~/x"}])
        out = self._run_reminder(root, "other")
        self.assertEqual(out.strip(), "")

    def test_match_no_quiz_nudge_without_activity(self):
        root = make_vault([{"slug": "svc", "globs": ["*/svc*"], "memdir": "-s", "repo": "~/x"}])
        out = self._run_reminder(root, "svc")
        self.assertIn("run /palace update", out)
        self.assertNotIn("Also", out)

    def test_match_quiz_nudge_when_active_and_never_quizzed(self):
        root = make_vault([{"slug": "svc", "globs": ["*/svc*"], "memdir": "-s", "repo": "~/x"}])
        repo = root / "repo"
        repo.mkdir()
        subprocess.run(["git", "init", "-q", str(repo)], check=True)
        (repo / "f.txt").write_text("x")
        subprocess.run(["git", "-C", str(repo), "add", "."], check=True)
        subprocess.run(["git", "-C", str(repo), "-c", "user.email=t@t", "-c", "user.name=t",
                        "commit", "-q", "-m", "c"], check=True)
        (root / "projects" / "_mapping.json").write_text(json.dumps({"projects": [
            {"slug": "svc", "globs": ["*/svc*"], "memdir": "-s", "repo": str(repo)}]}, indent=2))
        out = self._run_reminder(root, "svc")
        self.assertIn("Also", out)


class DoctorQuizNoteTests(unittest.TestCase):
    def test_never_quizzed_wing_gets_note(self):
        root = make_vault([{"slug": "alpha", "globs": ["*/alpha*"], "memdir": "-a", "repo": "~/a"}])
        # Create a git repo with a commit so the wing has activity → status becomes "ok"
        repo = root / "repo"
        repo.mkdir()
        subprocess.run(["git", "init", "-q", str(repo)], check=True)
        (repo / "f.txt").write_text("x")
        subprocess.run(["git", "-C", str(repo), "add", "."], check=True)
        subprocess.run(["git", "-C", str(repo), "-c", "user.email=t@t", "-c", "user.name=t",
                        "commit", "-q", "-m", "c"], check=True)
        (root / "projects" / "_mapping.json").write_text(json.dumps({"projects": [
            {"slug": "alpha", "globs": ["*/alpha*"], "memdir": "-a", "repo": str(repo)}]}, indent=2))
        out = run(root, "doctor")[1]
        self.assertIn("never quizzed", out)


class SearchTests(unittest.TestCase):
    def _wing_with_aq(self, root, slug, relpath, queries, key="anticipated_queries"):
        d = root / "projects" / slug / relpath
        d.parent.mkdir(parents=True, exist_ok=True)
        text = f"---\ntags: [project]\nproject: {slug}\n{key}:\n"
        for q in queries:
            text += f'  - "{q}"\n'
        text += "---\n# doc\n"
        d.write_text(text)

    def test_present_frontmatter_matches(self):
        root = make_vault([{"slug": "alpha", "globs": ["*/alpha*"], "memdir": "-a", "repo": "~/a"}])
        self._wing_with_aq(root, "alpha", "CONTEXT.md",
                            ["what's the current focus", "what's blocked right now"])
        rc, out, _ = run(root, "search", "current focus", "--slug", "alpha")
        self.assertEqual(rc, 0)
        self.assertIn("alpha/CONTEXT.md", out)
        self.assertIn("current focus", out)

    def test_absent_frontmatter_no_match(self):
        root = make_vault([{"slug": "alpha", "globs": ["*/alpha*"], "memdir": "-a", "repo": "~/a"}])
        out = run(root, "search", "anything at all here", "--slug", "alpha")[1]
        self.assertIn("no matches", out)

    def test_malformed_frontmatter_no_crash(self):
        root = make_vault([{"slug": "alpha", "globs": ["*/alpha*"], "memdir": "-a", "repo": "~/a"}])
        (root / "projects" / "alpha" / "BUGS.md").write_text(
            '---\nanticipated_queries: "not a list"\n---\n# bugs\n')
        rc, out, _ = run(root, "search", "bugs", "--slug", "alpha")
        self.assertEqual(rc, 0)

    def test_non_utf8_file_no_crash(self):
        """Verify anticipated_queries tolerates non-UTF-8 file content and doesn't crash.
        This tests the fix for UnicodeDecodeError that wasn't caught before."""
        root = make_vault([{"slug": "alpha", "globs": ["*/alpha*"], "memdir": "-a", "repo": "~/a"}])
        # Write a file with non-UTF-8 bytes (\xe9 is invalid UTF-8 continuation).
        # The file has valid frontmatter with anticipated_queries, but contains bad bytes.
        (root / "projects" / "alpha" / "GLOSSARY.md").write_bytes(
            b'---\ntags: [project]\nproject: alpha\nanticipated_queries:\n  - "caf\xe9 test"\n---\n# doc\n'
        )
        # Search should not crash; it should exit 0 and handle the file gracefully.
        rc, out, _ = run(root, "search", "cafe", "--slug", "alpha")
        self.assertEqual(rc, 0)

    def test_slug_scope_excludes_other_wings(self):
        root = make_vault([
            {"slug": "alpha", "globs": ["*/alpha*"], "memdir": "-a", "repo": "~/a"},
            {"slug": "beta", "globs": ["*/beta*"], "memdir": "-b", "repo": "~/b"},
        ])
        self._wing_with_aq(root, "alpha", "DECISIONS.md", ["why did we pick postgres"])
        self._wing_with_aq(root, "beta", "DECISIONS.md", ["why did we pick postgres"])
        out = run(root, "search", "postgres", "--slug", "alpha")[1]
        self.assertIn("alpha/DECISIONS.md", out)
        self.assertNotIn("beta/DECISIONS.md", out)

    def test_all_scope_includes_every_wing(self):
        root = make_vault([
            {"slug": "alpha", "globs": ["*/alpha*"], "memdir": "-a", "repo": "~/a"},
            {"slug": "beta", "globs": ["*/beta*"], "memdir": "-b", "repo": "~/b"},
        ])
        self._wing_with_aq(root, "alpha", "DECISIONS.md", ["why did we pick postgres"])
        self._wing_with_aq(root, "beta", "DECISIONS.md", ["why did we pick postgres"])
        out = run(root, "search", "postgres", "--all")[1]
        self.assertIn("alpha/DECISIONS.md", out)
        self.assertIn("beta/DECISIONS.md", out)

    def test_features_subdir_included(self):
        root = make_vault([{"slug": "alpha", "globs": ["*/alpha*"], "memdir": "-a", "repo": "~/a"}])
        self._wing_with_aq(root, "alpha", "features/billing.md",
                            ["how does billing retry failed charges"])
        out = run(root, "search", "billing retry", "--slug", "alpha")[1]
        self.assertIn("alpha/features/billing.md", out)

    def test_spine_feature_doc_included(self):
        """Spine docs live at <wing>/<repo dir>/<feature>/ and list their questions under `answers:`."""
        root = make_vault([{"slug": "alpha", "globs": ["*/alpha*"], "memdir": "-a",
                            "repos": [{"remote": "alpha-api", "path": "~/a", "dir": "alpha-api"}]}])
        self._wing_with_aq(root, "alpha", "alpha-api/billing/Architecture - Retries.md",
                            ["how does billing retry failed charges"], key="answers")
        out = run(root, "search", "billing retry", "--slug", "alpha")[1]
        self.assertIn("alpha/alpha-api/billing/Architecture - Retries.md", out)

    def test_backups_excluded(self):
        root = make_vault([{"slug": "alpha", "globs": ["*/alpha*"], "memdir": "-a", "repo": "~/a"}])
        self._wing_with_aq(root, "alpha", "_backups/2026-09-24/CONTEXT.md", ["what is blocked right now"])
        out = run(root, "search", "blocked right now", "--slug", "alpha")[1]
        self.assertIn("no matches", out)

    def test_top_8_cap(self):
        root = make_vault([{"slug": "alpha", "globs": ["*/alpha*"], "memdir": "-a", "repo": "~/a"}])
        for i in range(10):
            self._wing_with_aq(root, "alpha", f"features/f{i}.md", [f"widget topic {i}"])
        out = run(root, "search", "widget topic", "--slug", "alpha")[1]
        self.assertEqual(len(out.strip().splitlines()), 8)

    def test_tied_scores_ordered_deterministically(self):
        root = make_vault([
            {"slug": "beta", "globs": ["*/beta*"], "memdir": "-b", "repo": "~/b"},
            {"slug": "alpha", "globs": ["*/alpha*"], "memdir": "-a", "repo": "~/a"},
        ])
        self._wing_with_aq(root, "beta", "features/z.md", ["widget topic tie"])
        self._wing_with_aq(root, "alpha", "features/a.md", ["widget topic tie"])
        expected = run(root, "search", "widget topic tie", "--all")[1]
        for _ in range(5):
            self.assertEqual(run(root, "search", "widget topic tie", "--all")[1], expected)
        self.assertEqual(
            expected.strip().splitlines()[0].split(" — ")[0], "alpha/features/a.md")


if __name__ == "__main__":
    unittest.main(verbosity=2)


class SpinePalaceLinkTests(unittest.TestCase):
    SCRIPT = REPO_ROOT / "hooks" / "spine-palace-link.py"

    def test_accepts_wing_slug_from_any_cwd(self):
        root = Path(tempfile.mkdtemp())
        doc = root / "projects" / "alpha" / "alpha-api" / "billing" / "Billing.md"
        doc.parent.mkdir(parents=True)
        doc.write_text("---\ntitle: Billing\ntags:\n  - alpha-api\n  - billing\n---\n# Billing\n")
        env = {**os.environ, "VAULT_DIR": str(root)}
        r = subprocess.run(["python3", str(self.SCRIPT), "alpha"], capture_output=True, text=True,
                           env=env, cwd=tempfile.mkdtemp())
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertTrue((root / "projects" / "alpha" / "_features.md").is_file())
