#!/usr/bin/env python3
"""Tests for the palace engine — palace-map resolution/validate/render/staleness/archive.

Each test builds a throwaway fixture vault in a tempdir and drives the REAL engine
scripts (`palace-map`, `palace-context.sh`) as subprocesses with VAULT_DIR pointed at
the fixture. Stdlib unittest only — runs on /usr/bin/python3 with zero install.

    python3 -m unittest -v        (from this dir)
"""
import json
import os
import subprocess
import tempfile
import time
import unittest
from pathlib import Path

CLAUDE_DIR = Path(os.path.expanduser("~/.claude"))
PALACE_MAP = CLAUDE_DIR / "hooks" / "palace-map"
PALACE_CONTEXT = CLAUDE_DIR / "hooks" / "palace-context.sh"
TABLE_BEGIN = "<!-- palace-map:table:begin — generated by `palace-map render`, do not edit by hand -->"
TABLE_END = "<!-- palace-map:table:end -->"

WING_FILES = ["readme.md", "ARCHITECTURE.md", "BUGS.md", "CONTEXT.md", "DECISIONS.md"]


def make_wing(projects: Path, slug: str, status: str = "active"):
    d = projects / slug
    d.mkdir(parents=True, exist_ok=True)
    (d / "readme.md").write_text(f"---\ntags: [project]\nproject: {slug}\nstatus: {status}\n---\n# {slug}\n")
    (d / "CONTEXT.md").write_text(f"---\nproject: {slug}\n---\n# Context — {slug}\n\n## Current Focus\nstuff\n")
    for f in ("ARCHITECTURE.md", "BUGS.md", "DECISIONS.md"):
        (d / f).write_text(f"# {f} — {slug}\n")
    return d


def make_vault(entries, wings=None, with_markers=True):
    """entries: list of mapping dicts. wings: slugs to create wing dirs for
    (defaults to every entry's slug)."""
    root = Path(tempfile.mkdtemp(prefix="palace-fix-"))
    projects = root / "projects"
    projects.mkdir(parents=True)
    (root / "claude-sessions").mkdir()
    (projects / "_mapping.json").write_text(json.dumps({"projects": entries}, indent=2))
    md = "# Map\n\nintro\n\n"
    md += (TABLE_BEGIN + "\n" + TABLE_END + "\n") if with_markers else "no markers here\n"
    md += "\n## Notes\ntail\n"
    (projects / "_mapping.md").write_text(md)
    for slug in (wings if wings is not None else [e["slug"] for e in entries]):
        make_wing(projects, slug)
    return root


def run(root, *args, extra_env=None, cwd=None):
    env = {**os.environ, "VAULT_DIR": str(root)}
    if extra_env:
        env.update(extra_env)
    r = subprocess.run([str(PALACE_MAP), *args], capture_output=True, text=True, env=env, cwd=cwd)
    return r.returncode, r.stdout, r.stderr


class ResolveTests(unittest.TestCase):
    def test_matches_and_nonmatch(self):
        root = make_vault([
            {"slug": "alpha", "globs": ["*/alpha*"], "memdir": "-a", "repo": "~/alpha"},
            {"slug": "beta", "globs": ["*/theTribe/beta*"], "memdir": "-b", "repo": "~/beta"},
        ])
        self.assertEqual(run(root, "resolve", "/x/alpha/y")[1].strip(), "alpha")
        self.assertEqual(run(root, "resolve", "/home/theTribe/beta")[1].strip(), "beta")
        self.assertEqual(run(root, "resolve", "/nope/here")[1].strip(), "")

    def test_first_match_wins_ordering(self):
        # broad glob listed BEFORE the narrower one → broad must win (locks semantics)
        root = make_vault([
            {"slug": "broad", "globs": ["*/shared*"], "memdir": "-x", "repo": "~/x"},
            {"slug": "narrow", "globs": ["*/shared/sub*"], "memdir": "-y", "repo": "~/y"},
        ])
        self.assertEqual(run(root, "resolve", "/shared/sub/z")[1].strip(), "broad")


class ValidateTests(unittest.TestCase):
    def test_clean_ok(self):
        root = make_vault([{"slug": "alpha", "globs": ["*/alpha*"], "memdir": "-a", "repo": "~/a"}])
        rc, out, _ = run(root, "validate")
        self.assertEqual(rc, 0)
        self.assertIn("OK", out)

    def test_orphan_mapping_errors(self):
        # entry with no wing dir → ERROR + exit 1 (the gallia bug)
        root = make_vault(
            [{"slug": "ghost", "globs": ["*/ghost*"], "memdir": "-g", "repo": "~/g"}],
            wings=[],  # create no wing dirs
        )
        rc, out, _ = run(root, "validate")
        self.assertEqual(rc, 1)
        self.assertIn("ERROR", out)

    def test_unwired_wing_warns(self):
        # wing dir present but not in _mapping.json → WARN, exit 0 (the dev/swizzin bug)
        root = make_vault([{"slug": "alpha", "globs": ["*/alpha*"], "memdir": "-a", "repo": "~/a"}])
        make_wing(root / "projects", "stray")
        rc, out, _ = run(root, "validate")
        self.assertEqual(rc, 0)
        self.assertIn("WARN", out)


class RenderTests(unittest.TestCase):
    def test_idempotent(self):
        root = make_vault([{"slug": "alpha", "globs": ["*/alpha*"], "memdir": "-a", "repo": "~/a"}])
        md = root / "projects" / "_mapping.md"
        self.assertEqual(run(root, "render")[0], 0)
        first = md.read_text()
        self.assertEqual(run(root, "render")[0], 0)
        self.assertEqual(md.read_text(), first, "render must be idempotent")
        self.assertIn("`alpha`", first)

    def test_missing_markers_errors(self):
        root = make_vault([{"slug": "alpha", "globs": ["*/alpha*"], "memdir": "-a", "repo": "~/a"}],
                          with_markers=False)
        rc, out, _ = run(root, "render")
        self.assertEqual(rc, 1)
        self.assertIn("markers", out.lower())


class ArchiveTests(unittest.TestCase):
    def test_roundtrip(self):
        root = make_vault([{"slug": "alpha", "globs": ["*/alpha*"], "memdir": "-a", "repo": "~/a"}])
        readme = root / "projects" / "alpha" / "readme.md"
        run(root, "archive", "alpha")
        self.assertIn("status: archived", readme.read_text())
        run(root, "unarchive", "alpha")
        self.assertIn("status: active", readme.read_text())
        self.assertNotIn("status: archived", readme.read_text())


class StalenessTests(unittest.TestCase):
    """Drives palace-context.sh: a git repo with a commit newer than CONTEXT.md must
    trigger the staleness banner; a fresh CONTEXT.md must not."""

    def _git_repo_wing(self, root, slug, ctx_age_days):
        repo = root / "repo"
        repo.mkdir()
        subprocess.run(["git", "init", "-q", str(repo)], check=True)
        (repo / "f.txt").write_text("x")
        subprocess.run(["git", "-C", str(repo), "add", "."], check=True)
        subprocess.run(["git", "-C", str(repo), "-c", "user.email=t@t", "-c", "user.name=t",
                        "commit", "-q", "-m", "c"], check=True)
        # point the mapping's repo at the git repo, glob at a matchable cwd
        (root / "projects" / "_mapping.json").write_text(json.dumps({"projects": [
            {"slug": slug, "globs": [f"*/{slug}*"], "memdir": "-s", "repo": str(repo)}]}, indent=2))
        ctx = root / "projects" / slug / "CONTEXT.md"
        t = time.time() - ctx_age_days * 86400
        os.utime(ctx, (t, t))
        return repo

    def _run_context(self, root, cwd):
        env = {**os.environ, "VAULT_DIR": str(root), "PALACE_CLAUDE_DIR": str(CLAUDE_DIR)}
        work = root / cwd
        work.mkdir(parents=True, exist_ok=True)
        r = subprocess.run(["bash", str(PALACE_CONTEXT)], capture_output=True, text=True,
                           env=env, cwd=str(work))
        return r.stdout

    def test_stale_warns(self):
        root = make_vault([{"slug": "svc", "globs": ["*/svc*"], "memdir": "-s", "repo": "~/x"}])
        self._git_repo_wing(root, "svc", ctx_age_days=30)  # CONTEXT 30d older than commit
        out = self._run_context(root, "svc")
        self.assertIn("Palace Context — svc", out)
        self.assertIn("stale", out.lower())

    def test_fresh_no_warn(self):
        root = make_vault([{"slug": "svc", "globs": ["*/svc*"], "memdir": "-s", "repo": "~/x"}])
        self._git_repo_wing(root, "svc", ctx_age_days=0)  # CONTEXT as new as the commit
        out = self._run_context(root, "svc")
        self.assertIn("Palace Context — svc", out)
        self.assertNotIn("stale", out.lower())


class SystemDoctorTests(unittest.TestCase):
    def test_broken_install_flags_red(self):
        # Point PALACE_CLAUDE_DIR at an empty dir → settings/hooks/paths all missing → exit 1.
        root = make_vault([{"slug": "alpha", "globs": ["*/alpha*"], "memdir": "-a", "repo": "~/a"}])
        empty_claude = Path(tempfile.mkdtemp(prefix="palace-claude-"))
        rc, out, _ = run(root, "doctor", "--system",
                         extra_env={"PALACE_CLAUDE_DIR": str(empty_claude)})
        self.assertEqual(rc, 1)
        self.assertIn("RED", out)
        self.assertIn("✗", out)

    def test_live_install_green(self):
        # Sanity: the real install should be all-green (no fixture override).
        env = {**os.environ}
        env.pop("VAULT_DIR", None)
        r = subprocess.run([str(PALACE_MAP), "doctor", "--system"],
                           capture_output=True, text=True, env=env)
        self.assertEqual(r.returncode, 0, r.stdout)
        self.assertIn("ALL GREEN", r.stdout)


if __name__ == "__main__":
    unittest.main(verbosity=2)
