#!/usr/bin/env python3
"""Wire a palace wing to its spine feature docs.

Two directions, both idempotent:
  up   - every spine feature doc gets `wing: <name>` in its frontmatter
  down - the wing gets a generated `_features.md` index, and each palace root
         doc gets a one-line pointer to it

Wing-agnostic: nothing here is specific to one project. A wing with no spine
feature docs is skipped, so this is safe to run across the whole vault.

Usage:
  spine-palace-link.py <wing-dir> [--dry-run]
  spine-palace-link.py --all [--dry-run]      # every wing under projects/
"""
import json
import os
import re
import sys

PALACE_ROOTS = {"ARCHITECTURE.md", "CONTEXT.md", "DECISIONS.md", "BUGS.md", "GLOSSARY.md"}
SKIP_DIRS = {"_backups", ".obsidian", ".spine", ".git"}
INDEX = "_features.md"
BEGIN = "<!-- spine-index:begin — generated by spine-palace-link.py, do not edit by hand -->"
END = "<!-- spine-index:end -->"
POINTER_MARK = "<!-- spine-pointer -->"


def vault_prefix(wing):
    """Wikilinks resolve from the vault root, so links must be prefixed with the
    wing's path relative to the nearest ancestor holding `.obsidian`. Returns ''
    when the wing is itself the vault root."""
    cur = wing
    while True:
        if os.path.isdir(os.path.join(cur, ".obsidian")):
            rel = os.path.relpath(wing, cur)
            return "" if rel == "." else rel + "/"
        parent = os.path.dirname(cur)
        if parent == cur:
            return ""  # no vault root found, fall back to wing-relative
        cur = parent


def repo_labels(wing):
    """dir -> human label, from _mapping.json.

    Spine forces the on-disk dir to be the git remote basename (`frontend`,
    `sentinelles_de_la_nature`), which reads badly. The mapping can carry a
    `label` so the generated index shows the name a human would use."""
    mapping = os.path.join(os.path.dirname(wing), "_mapping.json")
    if not os.path.exists(mapping):
        return {}
    try:
        with open(mapping, encoding="utf-8") as fh:
            projects = json.load(fh)["projects"]
    except (OSError, ValueError, KeyError):
        return {}
    e = next((p for p in projects if p["slug"] == os.path.basename(wing)), None)
    return {r["dir"]: r.get("label") or r["dir"]
            for r in (e or {}).get("repos", []) if r.get("dir")}


def scan(wing):
    """-> {feature: {repo: [(title, wikilink_target)]}}"""
    prefix = vault_prefix(wing)
    features = {}
    for repo in sorted(os.listdir(wing)):
        repo_path = os.path.join(wing, repo)
        if repo in SKIP_DIRS or not os.path.isdir(repo_path):
            continue
        for feat in sorted(os.listdir(repo_path)):
            feat_path = os.path.join(repo_path, feat)
            if not os.path.isdir(feat_path):
                continue
            docs = sorted(f for f in os.listdir(feat_path) if f.endswith(".md"))
            if not docs:
                continue
            for doc in docs:
                stem = doc[:-3]
                # path-qualified from the vault root: titles repeat across repos
                # (Auth, Forms, Campaigns all exist in several), so bare names are
                # ambiguous and Obsidian would resolve them arbitrarily.
                target = f"{prefix}{repo}/{feat}/{stem}"
                features.setdefault(feat, {}).setdefault(repo, []).append((stem, target))
    return features


def render_index(wing_name, features, labels=None):
    labels = labels or {}
    total = sum(len(d) for r in features.values() for d in r.values())
    out = [
        "---",
        "tags: [meta, spine-index]",
        f"project: {wing_name}",
        "---",
        f"# Feature index — {wing_name}",
        "",
        "> Generated. Palace root docs hold the cross-cutting view, spine feature docs",
        "> hold the depth. This file is the bridge: find the feature, then read down.",
        "> Regenerate with `spine-palace-link.py`.",
        "",
        BEGIN,
        f"**{len(features)} features, {total} docs.**",
        "",
    ]
    for feat in sorted(features):
        repos = features[feat]
        count = sum(len(v) for v in repos.values())
        spread = ", ".join(f"{labels.get(r, r)} ({len(repos[r])})" for r in sorted(repos))
        out.append(f"## {feat}")
        out.append(f"*{count} docs across {spread}*")
        out.append("")
        for repo in sorted(repos):
            for title, target in repos[repo]:
                out.append(f"- `{labels.get(repo, repo)}` [[{target}|{title}]]")
        out.append("")
    out.append(END)
    return "\n".join(out) + "\n"


def add_wing_field(path, wing_name):
    """Insert `wing: <name>` into existing frontmatter. Idempotent."""
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    if not text.startswith("---\n"):
        return False  # no frontmatter, leave it alone
    end = text.find("\n---", 4)
    if end == -1:
        return False
    head = text[4:end]
    if re.search(r"^wing:", head, re.M):
        return False
    # place it right after title: if present, else at the top of the block
    lines = head.split("\n")
    idx = next((i for i, l in enumerate(lines) if l.startswith("title:")), -1)
    lines.insert(idx + 1, f"wing: {wing_name}")
    new = "---\n" + "\n".join(lines) + text[end:]
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(new)
    return True


def add_pointer(path, wing_name, prefix=""):
    """Add a pointer line below the H1 of a palace root doc. Idempotent."""
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    if POINTER_MARK in text:
        return False
    line = (
        f"{POINTER_MARK}\n> Depth lives in the spine feature docs, indexed in "
        f"[[{prefix}_features|{wing_name} feature index]]. This file holds the cross-cutting view.\n"
    )
    m = re.search(r"^# .+$", text, re.M)
    if not m:
        return False
    at = m.end()
    new = text[:at] + "\n\n" + line + text[at:]
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(new)
    return True


def projects_dir():
    """Vault root from palace.env, same precedence the bash hooks use."""
    vault = os.environ.get("VAULT_DIR")
    if not vault:
        env = os.path.expanduser("~/.claude/palace.env")
        if os.path.exists(env):
            with open(env, encoding="utf-8") as fh:
                for line in fh:
                    if line.startswith("VAULT_DIR="):
                        vault = line.split("=", 1)[1].strip()
                        break
    return os.path.join(os.path.expanduser(vault or "~/obsidian"), "projects")


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    dry = "--dry-run" in sys.argv

    if "--all" in sys.argv:
        root = projects_dir()
        wings = sorted(
            os.path.join(root, d) for d in os.listdir(root)
            if os.path.isdir(os.path.join(root, d)) and not d.startswith((".", "_"))
        )
        done = skipped = 0
        for w in wings:
            if not scan(w):
                skipped += 1
                continue
            print(f"--- {os.path.basename(w)} ---")
            process(w, dry)
            done += 1
        print(f"\n{done} wing(s) linked, {skipped} skipped (no spine docs)")
        return

    if not args:
        sys.exit("usage: spine-palace-link.py <wing-dir>|--all [--dry-run]")
    wing = os.path.abspath(os.path.expanduser(args[0]))
    if not os.path.isdir(wing):
        sys.exit(f"not a directory: {wing}")
    if not scan(wing):
        sys.exit(f"no spine feature docs found under {wing}")
    process(wing, dry)


def process(wing, dry):
    wing_name = os.path.basename(wing)
    prefix = vault_prefix(wing)
    features = scan(wing)
    index_text = render_index(wing_name, features, repo_labels(wing))
    index_path = os.path.join(wing, INDEX)

    upped = 0
    for repos in features.values():
        for docs in repos.values():
            for _, target in docs:
                # targets are vault-root-relative, filesystem paths are wing-relative
                p = os.path.join(wing, target[len(prefix):] + ".md")
                if dry:
                    with open(p, encoding="utf-8") as fh:
                        if not re.search(r"^wing:", fh.read()[:400], re.M):
                            upped += 1
                elif add_wing_field(p, wing_name):
                    upped += 1

    pointed = []
    for root in sorted(PALACE_ROOTS):
        p = os.path.join(wing, root)
        if not os.path.exists(p):
            continue
        if dry:
            with open(p, encoding="utf-8") as fh:
                if POINTER_MARK not in fh.read():
                    pointed.append(root)
        elif add_pointer(p, wing_name, prefix):
            pointed.append(root)

    if not dry:
        with open(index_path, "w", encoding="utf-8") as fh:
            fh.write(index_text)

    verb = "would write" if dry else "wrote"
    total = sum(len(d) for r in features.values() for d in r.values())
    print(f"{verb} {INDEX}: {len(features)} features, {total} docs")
    print(f"{verb} `wing: {wing_name}` into {upped} spine docs")
    print(f"{verb} pointer into: {', '.join(pointed) if pointed else '(none, all present)'}")


if __name__ == "__main__":
    main()
